services:
  dockerhealthmonitor.webapi:
    image: ${DOCKER_REGISTRY-}dockerhealthmonitorwebapi
    build:
      context: .
      dockerfile: DockerHealthMonitor.WebApi/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERPROFILE}\.aspnet\https:/https:ro
    user: "0:0"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=B59ELMFIIU96L75XCKXA
